FROM golang:1.24.2-alpine AS builder

RUN apk add --no-cache gcc musl-dev libwebp-dev jpeg-dev

WORKDIR /app

RUN go env -w GOPROXY=https://goproxy.io,direct

COPY go.mod go.sum ./

RUN go mod download -x

COPY . .

RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s " -o nanny ./cmd/el-nanny

FROM alpine:3.21

RUN apk add --no-cache ca-certificates tzdata libwebp-dev jpeg-dev

WORKDIR /app

COPY --from=builder /app/nanny .

COPY .env .

CMD ["./nanny"]