services:
  db:
    image: postgres:17
    container_name: postgres_container
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: niflheim
      POSTGRES_PASSWORD: niflguard
      POSTGRES_DB: bidlancer
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    volumes:
      - redisdata:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - backend_network

  app:
    build: .
    image: ghcr.io/niflheimdevs/backend
    container_name: application
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    volumes:
      -storagedata:./storage
    ports:
      - "8080:8080"
    networks:
      - backend_network


volumes:
  pgdata:
  redisdata:
  storagedata:

networks:
  backend_network:
    driver: bridge
