FROM confluentinc/cp-kafka-connect-base:7.6.0

ARG DEBEZIUM_VERSION=3.0.8.Final-redhat-00004

RUN apk add --no-cache unzip

RUN curl -fSL https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-postgres/${DEBEZIUM_VERSION}/debezium-connector-postgres-${DEBEZIUM_VERSION}-plugin.zip -o plugin.zip \
    && unzip plugin.zip -d /kafka/connect/ \
    && rm plugin.zip