

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./migrations/triggers.sql:/docker-entrypoint-initdb.d/02-triggers.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    volumes:
      - redisdata:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - backend_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/niflheimdevs/backend
    container_name: application
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    networks:
      - backend_network

  el-nanny:
    build:
      context: .
      dockerfile: Dockerfile.ElasticNanny
    image: ghcr.io/niflheimdevs/el-nanny
    container_name: el-nanny
    restart: always
    depends_on:
      - elasticsearch
      - kafka
    env_file:
      - ./.env
    networks:
      - backend_network


  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend_network

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - backend_network

  debezium:
    image: debezium/connect:2.5
    container_name: debezium
    depends_on:
      - kafka
      - db
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connect_configs
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_statuses
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
    networks:
      - backend_network

  debezium-init:
    image: curlimages/curl:latest
    container_name: debezium_init
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      TOPIC_PREFIX_DB: ${TOPIC_PREFIX_DB}
    depends_on:
      - debezium
    volumes:
      - ./register-debezium.sh:/register-debezium.sh
    entrypoint: ["sh", "/register-debezium.sh"]
    networks:
      - backend_network

  elasticsearch:
    image: elasticsearch:7.17.13
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - backend_network
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  pgdata:
  redisdata:
  esdata:

networks:
  backend_network:
    driver: bridge
