FROM debezium/connect-base:2.5

ENV DEBEZIUM_VERSION=3.0.8.Final-redhat-00004

RUN cat /etc/os-release

RUN microdnf install -y dnf && dnf install -y unzip curl && dnf clean all

RUN curl -L https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-postgres/${DEBEZIUM_VERSION}/debezium-connector-postgres-${DEBEZIUM_VERSION}-plugin.zip \
    -o /tmp/plugin.zip && \
    unzip /tmp/plugin.zip -d /kafka/connect && \
    rm /tmp/plugin.zip