// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/niflheimdevs/backend/internal/bootstrap"
	"github.com/niflheimdevs/backend/internal/handlers"
	"github.com/niflheimdevs/backend/internal/middlewares/authentication"
	"github.com/niflheimdevs/backend/internal/middlewares/exceptions"
	"github.com/niflheimdevs/backend/internal/middlewares/ratelimit"
	"github.com/niflheimdevs/backend/internal/repositories"
	redis2 "github.com/niflheimdevs/backend/internal/repositories/redis"
	"github.com/niflheimdevs/backend/internal/repositories/storage"
	"github.com/niflheimdevs/backend/internal/services"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Di, db *pgxpool.Pool, myRedis *redis.Client) (*Application, error) {
	constants := ProvideConstants(container)
	fileStorage := &storage.FileStorage{
		Constants: constants,
	}
	fileService := &services.FileService{
		FileStorage: fileStorage,
	}
	validate := handlers.NewValidator()
	jwt := services.NewJWT(constants)
	fileHandler := &handlers.FileHandler{
		FileService: fileService,
		Validator:   validate,
		JWTService:  jwt,
		Constants:   constants,
	}
	userRepo := &repositories.UserRepo{
		PG: db,
	}
	userCache := &redis2.UserCache{
		DB: myRedis,
	}
	userService := &services.UserService{
		UserRepo:    userRepo,
		CacheRepo:   userCache,
		Constants:   constants,
		FileService: fileService,
	}
	generalRepo := &repositories.GeneralRepo{
		PG: db,
	}
	generalService := &services.GeneralService{
		GeneralRepo: generalRepo,
		UserRepo:    userRepo,
	}
	userHandler := &handlers.UserHandler{
		Constants:      constants,
		UserService:    userService,
		JWTService:     jwt,
		Validator:      validate,
		GeneralService: generalService,
	}
	errorHandler := &handlers.ErrorHandler{}
	projectRepo := &repositories.ProjectRepo{
		PG: db,
	}
	paymentRepo := &repositories.PaymentRepo{
		PG: db,
	}
	paymentService := &services.PaymentService{
		PaymentRepo: paymentRepo,
	}
	projectService := &services.ProjectService{
		ProjectRepo:    projectRepo,
		PaymentService: paymentService,
		Constants:      constants,
	}
	projectHandler := &handlers.ProjectHandler{
		Constants:      constants,
		ProjectService: projectService,
		UserService:    userService,
		GeneralService: generalService,
		JWTService:     jwt,
		Validator:      validate,
	}
	generalHandler := &handlers.GeneralHandler{
		GeneralService: generalService,
		JWTService:     jwt,
		Constants:      constants,
		Validator:      validate,
	}
	paymentHandler := &handlers.PaymentHandler{
		PaymentService: paymentService,
		Constants:      constants,
		Validator:      validate,
	}
	panicWall := panicwall.NewPanicWall()
	rateLimit := midratelimit.NewRateLimit()
	authentication := midauth.NewAuth(constants, jwt)
	middlewares := &Middlewares{
		Recovery:       panicWall,
		RateLimit:      rateLimit,
		Authentication: authentication,
	}
	application := &Application{
		FileHandler:    fileHandler,
		UserHandler:    userHandler,
		ErrorHandler:   errorHandler,
		ProjectHandler: projectHandler,
		GeneralHandler: generalHandler,
		PaymentHandler: paymentHandler,
		Middlewares:    middlewares,
	}
	return application, nil
}

// wire.go:

var RepoProviderSet = wire.NewSet(wire.Struct(new(repositories.UserRepo), "*"), wire.Struct(new(repositories.ProjectRepo), "*"), wire.Struct(new(repositories.GeneralRepo), "*"), wire.Struct(new(redis2.UserCache), "*"), wire.Struct(new(storage.FileStorage), "*"), wire.Struct(new(repositories.PaymentRepo), "*"))

var ServiceProviderSet = wire.NewSet(wire.Struct(new(services.UserService), "*"), wire.Struct(new(services.FileService), "*"), wire.Struct(new(services.ProjectService), "*"), wire.Struct(new(services.GeneralService), "*"), wire.Struct(new(services.PaymentService), "*"), services.NewJWT, ProvideConstants)

var HandlerProviderSet = wire.NewSet(wire.Struct(new(handlers.UserHandler), "*"), wire.Struct(new(handlers.FileHandler), "*"), wire.Struct(new(handlers.ErrorHandler), "*"), wire.Struct(new(handlers.ProjectHandler), "*"), wire.Struct(new(handlers.GeneralHandler), "*"), wire.Struct(new(handlers.PaymentHandler), "*"), handlers.NewValidator)

var MiddlewareProviderSet = wire.NewSet(midratelimit.NewRateLimit, midauth.NewAuth, panicwall.NewPanicWall, wire.Struct(new(Middlewares), "*"))

func ProvideConstants(container *bootstrap.Di) *bootstrap.Constants {
	return container.Const
}

var ProviderSet = wire.NewSet(
	RepoProviderSet,
	ServiceProviderSet,
	HandlerProviderSet,
	MiddlewareProviderSet,
)

type Middlewares struct {
	Recovery       *panicwall.PanicWall
	RateLimit      *midratelimit.RateLimit
	Authentication *midauth.Authentication
}

type Application struct {
	FileHandler    *handlers.FileHandler
	UserHandler    *handlers.UserHandler
	ErrorHandler   *handlers.ErrorHandler
	ProjectHandler *handlers.ProjectHandler
	GeneralHandler *handlers.GeneralHandler
	PaymentHandler *handlers.PaymentHandler
	Middlewares    *Middlewares
}
