// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/niflheimdevs/backend/internal/bootstrap"
	"github.com/niflheimdevs/backend/internal/handlers"
	"github.com/niflheimdevs/backend/internal/middlewares/ratelimit"
	"github.com/niflheimdevs/backend/internal/repositories"
	"github.com/niflheimdevs/backend/internal/services"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Di, db *pgxpool.Pool) (*Application, error) {
	constants := ProvideConstants(container)
	userRepo := repositories.UserRepo{
		PG: db,
	}
	userService := services.UserService{
		UserRepo: userRepo,
	}
	jwtToken := services.JWTToken{}
	userHandler := &handlers.UserHandler{
		Constants:   constants,
		UserService: userService,
		JWTService:  jwtToken,
	}
	rateLimit := middleware_rate_limit.NewRateLimit()
	middlewares := &Middlewares{
		RateLimit: rateLimit,
	}
	application := &Application{
		UserHandler: userHandler,
		Middlewares: middlewares,
	}
	return application, nil
}

// wire.go:

var RepoProviderSet = wire.NewSet(wire.Struct(new(repositories.UserRepo), "*"))

var ServiceProviderSet = wire.NewSet(wire.Struct(new(services.UserService), "*"), wire.Struct(new(services.JWTToken), "*"))

var HandlerProviderSet = wire.NewSet(wire.Struct(new(handlers.UserHandler), "*"))

var MiddlewareProviderSet = wire.NewSet(middleware_rate_limit.NewRateLimit, wire.Struct(new(Middlewares), "*"))

func ProvideConstants(container *bootstrap.Di) *bootstrap.Constants {
	return container.Const
}

var ProviderSet = wire.NewSet(
	RepoProviderSet,
	ServiceProviderSet,
	HandlerProviderSet,
	MiddlewareProviderSet,
)

type Middlewares struct {
	RateLimit *middleware_rate_limit.RateLimit
}

type Application struct {
	UserHandler *handlers.UserHandler
	Middlewares *Middlewares
}
