// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/niflheimdevs/backend/internal/bootstrap"
	"github.com/niflheimdevs/backend/internal/handlers"
	"github.com/niflheimdevs/backend/internal/middlewares/authentication"
	"github.com/niflheimdevs/backend/internal/middlewares/exceptions"
	"github.com/niflheimdevs/backend/internal/middlewares/ratelimit"
	"github.com/niflheimdevs/backend/internal/repositories"
	redis2 "github.com/niflheimdevs/backend/internal/repositories/redis"
	"github.com/niflheimdevs/backend/internal/services"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Di, db *pgxpool.Pool, myRedis *redis.Client) (*Application, error) {
	constants := ProvideConstants(container)
	userRepo := &repositories.UserRepo{
		PG: db,
	}
	userCache := &redis2.UserCache{
		DB: myRedis,
	}
	userService := &services.UserService{
		UserRepo:  userRepo,
		CacheRepo: userCache,
	}
	jwtToken := &services.JWTToken{}
	validate := handlers.NewValidator()
	userHandler := &handlers.UserHandler{
		Constants:   constants,
		UserService: userService,
		JWTService:  jwtToken,
		Validator:   validate,
	}
	errorHandler := &handlers.ErrorHandler{}
	panicWall := panicwall.NewPanicWall()
	rateLimit := midratelimit.NewRateLimit()
	servicesJWTToken := services.JWTToken{}
	authentication := midauth.NewAuth(constants, servicesJWTToken)
	middlewares := &Middlewares{
		Recovery:       panicWall,
		RateLimit:      rateLimit,
		Authentication: authentication,
	}
	application := &Application{
		UserHandler:  userHandler,
		ErrorHandler: errorHandler,
		Middlewares:  middlewares,
	}
	return application, nil
}

// wire.go:

var RepoProviderSet = wire.NewSet(wire.Struct(new(repositories.UserRepo), "*"), wire.Struct(new(redis2.UserCache), "*"))

var ServiceProviderSet = wire.NewSet(wire.Struct(new(services.UserService), "*"), wire.Struct(new(services.JWTToken), "*"))

var HandlerProviderSet = wire.NewSet(wire.Struct(new(handlers.UserHandler), "*"), wire.Struct(new(handlers.ErrorHandler), "*"), handlers.NewValidator)

var MiddlewareProviderSet = wire.NewSet(midratelimit.NewRateLimit, midauth.NewAuth, panicwall.NewPanicWall, wire.Struct(new(Middlewares), "*"))

func ProvideConstants(container *bootstrap.Di) *bootstrap.Constants {
	return container.Const
}

var ProviderSet = wire.NewSet(
	RepoProviderSet,
	ServiceProviderSet,
	HandlerProviderSet,

	MiddlewareProviderSet,
)

type Middlewares struct {
	Recovery       *panicwall.PanicWall
	RateLimit      *midratelimit.RateLimit
	Authentication *midauth.Authentication
}

type Application struct {
	UserHandler  *handlers.UserHandler
	ErrorHandler *handlers.ErrorHandler
	Middlewares  *Middlewares
}
