CREATE TABLE IF NOT EXISTS "project" (
  "id" serial PRIMARY KEY,
  "owner_id" int NOT NULL,
  "title" text NOT NULL,
  "description" text,
  "label" int NOT NULL,
  "selected_bid_id" int UNIQUE,
  "status" int DEFAULT 1,
  "created_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_time" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "end_time" TIMESTAMP WITH TIME ZONE,
  "duration" TIMESTAMP WITH TIME ZONE,
  FOREIGN KEY ("owner_id") REFERENCES "users" ("id"),
  FOREIGN KEY ("selected_bid_id") REFERENCES "bid" ("id"),
  FOREIGN KEY ("label") REFERENCES "label" ("id"),
);