INSERT INTO tag (name) VALUES
('Data Structures'),
('Algorithms'),
('Operating Systems'),
('Computer Networks'),
('Database Management'),
('Cybersecurity'),
('Software Engineering'),
('Artificial Intelligence'),
('Machine Learning'),
('Deep Learning'),
('Cloud Computing'),
('Internet of Things (IoT)'),
('Embedded Systems'),
('Blockchain'),
('Quantum Computing'),
('DevOps'),
('System Design'),
('Parallel Computing'),
('High-Performance Computing'),
('Frontend Development'),
('Backend Development'),
('Full-Stack Development'),
('UI/UX Design'),
('Responsive Design'),
('Web Performance Optimization'),
('SEO'),
('Progressive Web Apps'),
('Serverless Architecture'),
('APIs & Microservices'),
('Authentication & Authorization'),
('Web Security'),
('WordPress'),
('Python'),
('JavaScript'),
('TypeScript'),
('Java'),
('C'),
('C++'),
('C#'),
('Go'),
('Rust'),
('PHP'),
('Swift'),
('Kotlin'),
('Dart'),
('Ruby'),
('Perl'),
('R'),
('MATLAB'),
('Scala'),
('Shell Scripting'),
('SQL'),
('NoSQL'),
('GraphQL'),
('HTML'),
('CSS'),
('Verilog'),
('VHDL');