// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/niflheimdevs/backend/bootstrap"
	"github.com/niflheimdevs/backend/internal/application/cdc/services"
	"github.com/niflheimdevs/backend/internal/application/cdc/services/impl"
	"github.com/niflheimdevs/backend/internal/application/services"
	"github.com/niflheimdevs/backend/internal/application/services/impl"
	"github.com/niflheimdevs/backend/internal/delivery/consumer"
	"github.com/niflheimdevs/backend/internal/delivery/handlers"
	"github.com/niflheimdevs/backend/internal/delivery/middlewares/authentication"
	"github.com/niflheimdevs/backend/internal/delivery/middlewares/exceptions"
	"github.com/niflheimdevs/backend/internal/delivery/middlewares/ratelimit"
	"github.com/niflheimdevs/backend/internal/delivery/middlewares/upgrader"
	"github.com/niflheimdevs/backend/internal/domain/repositories/elastic"
	"github.com/niflheimdevs/backend/internal/domain/repositories/postgres"
	"github.com/niflheimdevs/backend/internal/domain/repositories/postgres/transaction"
	"github.com/niflheimdevs/backend/internal/domain/repositories/redis"
	"github.com/niflheimdevs/backend/internal/domain/repositories/storage"
	"github.com/niflheimdevs/backend/internal/infrastructure/db/driver"
	"github.com/niflheimdevs/backend/internal/infrastructure/db/seed"
	"github.com/niflheimdevs/backend/internal/infrastructure/db/transaction"
	"github.com/niflheimdevs/backend/internal/infrastructure/repositories/elastic"
	"github.com/niflheimdevs/backend/internal/infrastructure/repositories/postgres"
	"github.com/niflheimdevs/backend/internal/infrastructure/repositories/redis"
	"github.com/niflheimdevs/backend/internal/infrastructure/repositories/storage"
	"github.com/niflheimdevs/backend/internal/infrastructure/websocket"
	"github.com/niflheimdevs/backend/pkg"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Di, hub *websocket.Hub) (*Application, error) {
	constants := ProvideConstants(container)
	env := ProvideEnv(container)
	s3 := ProvideS3(container)
	s3Storage := storageimpl.NewS3Storage(env, s3)
	fileService := servicesimpl.NewFileService(s3Storage)
	pool := driver.ConnectSQL(container)
	teamRepo := repositoriesimpl.NewTeamRepo(pool)
	userRepo := repositoriesimpl.NewUserRepo(pool)
	roleRepo := repositoriesimpl.NewRoleRepo(pool)
	pgxTxManager := db.NewTxManager(pool)
	teamService := servicesimpl.NewTeamService(teamRepo, userRepo, roleRepo, pgxTxManager, fileService)
	jwt := servicesimpl.NewJWT(constants)
	validate := pkg.NewValidator()
	fileHandler := handlers.NewFileHandler(constants, env, fileService, teamService, jwt, validate)
	client := driver.ConncetRedis(container)
	userCache := redisimpl.NewUserCache(client)
	secretSauce := pkg.NewSecretSauce()
	userService := servicesimpl.NewUserService(userRepo, userCache, pgxTxManager, constants, env, fileService, teamService, secretSauce)
	tagRepo := repositoriesimpl.NewTagRepo(pool)
	tagService := servicesimpl.NewTagService(tagRepo, userRepo)
	careerRepo := repositoriesimpl.NewCareerRepo(pool)
	careerService := servicesimpl.NewCareerService(careerRepo, tagService, tagRepo, userRepo)
	smsService := servicesimpl.NewSmsService(env, constants)
	userHandler := handlers.NewUserHandler(constants, userService, jwt, validate, tagService, careerService, smsService)
	projectRepo := repositoriesimpl.NewProjectRepo(pool, tagRepo)
	paymentRepo := repositoriesimpl.NewPaymentRepo(pool)
	paymentService := servicesimpl.NewPaymentService(paymentRepo, pgxTxManager)
	bidRepo := repositoriesimpl.NewBidRepo(pool)
	projectService := servicesimpl.NewProjectService(projectRepo, paymentService, constants, tagRepo, bidRepo, tagService, teamService, pgxTxManager)
	labelRepo := repositoriesimpl.NewLabelRepo(pool)
	labelService := servicesimpl.NewLabelService(labelRepo, userRepo)
	bidService := servicesimpl.NewBidService(projectService, paymentService, teamService, bidRepo, teamRepo, pgxTxManager)
	projectHandler := handlers.NewProjectHandler(constants, projectService, userService, labelService, bidService, jwt, validate)
	generalHandler := handlers.NewGeneralHandler(tagService, careerService, labelService, jwt, constants, validate)
	paymentHandler := handlers.NewPaymentHandler(paymentService, constants, validate)
	bidHandler := handlers.NewBidHandler(constants, validate, bidService, teamService)
	teamHandler := handlers.NewTeamHandler(teamService, constants, validate)
	roleService := servicesimpl.NewRoleService()
	roleHandler := handlers.NewRoleHandler(roleService, constants, validate)
	chatRepo := repositoriesimpl.NewChatRepo(pool)
	chatService := servicesimpl.NewChatService(pgxTxManager, chatRepo)
	chatHandler := handlers.NewChatHandler(validate, jwt, constants, hub, chatService)
	wireHandlers := &Handlers{
		FileHandler:    fileHandler,
		UserHandler:    userHandler,
		ProjectHandler: projectHandler,
		GeneralHandler: generalHandler,
		PaymentHandler: paymentHandler,
		BidHandler:     bidHandler,
		TeamHandler:    teamHandler,
		RoleHandler:    roleHandler,
		ChatHandler:    chatHandler,
	}
	panicWall := panicwall.NewPanicWall()
	rateLimit := midratelimit.NewRateLimit(constants)
	authentication := midauth.NewAuth(constants, jwt)
	webSocketUpgrader := midupgrader.NewWebSocketUpgrader(constants)
	middlewares := &Middlewares{
		Recovery:       panicWall,
		RateLimit:      rateLimit,
		Authentication: authentication,
		Upgrader:       webSocketUpgrader,
	}
	seeder := seed.NewSeeder(pgxTxManager)
	application := &Application{
		Handlers:    wireHandlers,
		Middlewares: middlewares,
		Seeder:      seeder,
	}
	return application, nil
}

func InitializeCdcConsumer(container *bootstrap.Di) (*ElasticApp, error) {
	pool := driver.ConnectSQL(container)
	tagRepo := repositoriesimpl.NewTagRepo(pool)
	client := driver.ConnectElastic(container)
	teamElastic := elasticimpl.NewTeamElastic(client)
	teamCdc := cdcservicesimpl.NewTeamCdc(tagRepo, teamElastic)
	projectElastic := elasticimpl.NewProjectElastic(client)
	projectCdc := cdcservicesimpl.NewProjectCdc(tagRepo, projectElastic)
	userElastic := elasticimpl.NewUserElastic(client)
	userCdc := cdcservicesimpl.NewUserCdc(tagRepo, userElastic)
	kafkaCdc := consumer.NewKafkaCdc(teamCdc, projectCdc, userCdc)
	elasticApp := &ElasticApp{
		KafkaCdc: kafkaCdc,
	}
	return elasticApp, nil
}

// wire.go:

var DatabaseProviderSet = wire.NewSet(driver.ConnectSQL, driver.ConncetRedis, db.NewTxManager, wire.Bind(new(transaction.TxManager), new(*db.PgxTxManager)))

var ElasticAndDatabaseProviderSet = wire.NewSet(driver.ConnectElastic, driver.ConnectSQL)

var PkgProviderSet = wire.NewSet(pkg.NewValidator, pkg.NewSecretSauce)

var RepoProviderSet = wire.NewSet(repositoriesimpl.NewUserRepo, repositoriesimpl.NewProjectRepo, repositoriesimpl.NewCareerRepo, repositoriesimpl.NewTagRepo, repositoriesimpl.NewLabelRepo, repositoriesimpl.NewPaymentRepo, repositoriesimpl.NewTeamRepo, repositoriesimpl.NewRoleRepo, repositoriesimpl.NewBidRepo, repositoriesimpl.NewChatRepo, storageimpl.NewS3Storage, redisimpl.NewUserCache, wire.Bind(new(repositories.UserRepo), new(*repositoriesimpl.UserRepo)), wire.Bind(new(repositories.TagRepo), new(*repositoriesimpl.TagRepo)), wire.Bind(new(repositories.CareerRepo), new(*repositoriesimpl.CareerRepo)), wire.Bind(new(repositories.LabelRepo), new(*repositoriesimpl.LabelRepo)), wire.Bind(new(repositories.ProjectRepo), new(*repositoriesimpl.ProjectRepo)), wire.Bind(new(repositories.PaymentRepo), new(*repositoriesimpl.PaymentRepo)), wire.Bind(new(repositories.BidRepo), new(*repositoriesimpl.BidRepo)), wire.Bind(new(repositories.TeamRepo), new(*repositoriesimpl.TeamRepo)), wire.Bind(new(repositories.RoleRepo), new(*repositoriesimpl.RoleRepo)), wire.Bind(new(repositories.ChatRepo), new(*repositoriesimpl.ChatRepo)), wire.Bind(new(storage.S3Storage), new(*storageimpl.S3Storage)), wire.Bind(new(redis.UserCache), new(*redisimpl.UserCache)))

var ElRepoProviderSet = wire.NewSet(repositoriesimpl.NewTagRepo, elasticimpl.NewProjectElastic, elasticimpl.NewUserElastic, elasticimpl.NewTeamElastic, wire.Bind(new(repositories.TagRepo), new(*repositoriesimpl.TagRepo)), wire.Bind(new(elastic.ProjectElastic), new(*elasticimpl.ProjectElastic)), wire.Bind(new(elastic.UserElastic), new(*elasticimpl.UserElastic)), wire.Bind(new(elastic.TeamElastic), new(*elasticimpl.TeamElastic)))

var FileServiceProviderSet = wire.NewSet(servicesimpl.NewFileService, wire.Bind(new(services.FileService), new(*servicesimpl.FileService)))

var ServiceProviderSet = wire.NewSet(servicesimpl.NewUserService, servicesimpl.NewTagService, servicesimpl.NewCareerService, servicesimpl.NewLabelService, servicesimpl.NewProjectService, servicesimpl.NewPaymentService, servicesimpl.NewTeamService, servicesimpl.NewBidService, servicesimpl.NewSmsService, servicesimpl.NewJWT, servicesimpl.NewRoleService, servicesimpl.NewChatService, wire.Bind(new(services.UserService), new(*servicesimpl.UserService)), wire.Bind(new(services.TagService), new(*servicesimpl.TagService)), wire.Bind(new(services.CareerService), new(*servicesimpl.CareerService)), wire.Bind(new(services.LabelService), new(*servicesimpl.LabelService)), wire.Bind(new(services.ProjectService), new(*servicesimpl.ProjectService)), wire.Bind(new(services.PaymentService), new(*servicesimpl.PaymentService)), wire.Bind(new(services.TeamService), new(*servicesimpl.TeamService)), wire.Bind(new(services.BidService), new(*servicesimpl.BidService)), wire.Bind(new(services.SmsService), new(*servicesimpl.SmsService)), wire.Bind(new(services.JWT), new(*servicesimpl.JWT)), wire.Bind(new(services.ChatService), new(*servicesimpl.ChatService)), wire.Bind(new(services.RoleService), new(*servicesimpl.RoleService)), ProvideConstants,
	ProvideEnv,
	ProvideS3,
)

var CdcServiceProviderSet = wire.NewSet(cdcservicesimpl.NewProjectCdc, cdcservicesimpl.NewUserCdc, cdcservicesimpl.NewTeamCdc, wire.Bind(new(cdcservices.ProjectCdc), new(*cdcservicesimpl.ProjectCdc)), wire.Bind(new(cdcservices.UserCdc), new(*cdcservicesimpl.UserCdc)), wire.Bind(new(cdcservices.TeamCdc), new(*cdcservicesimpl.TeamCdc)), ProvideConstants,
	ProvideEnv,
)

var HandlerProviderSet = wire.NewSet(handlers.NewFileHandler, handlers.NewUserHandler, handlers.NewProjectHandler, handlers.NewGeneralHandler, handlers.NewPaymentHandler, handlers.NewBidHandler, handlers.NewTeamHandler, handlers.NewRoleHandler, handlers.NewChatHandler, wire.Struct(new(Handlers), "*"))

var KafkaCdcProviderSet = wire.NewSet(consumer.NewKafkaCdc)

var MiddlewareProviderSet = wire.NewSet(midratelimit.NewRateLimit, midauth.NewAuth, panicwall.NewPanicWall, midupgrader.NewWebSocketUpgrader, wire.Struct(new(Middlewares), "*"))

func ProvideConstants(container *bootstrap.Di) *bootstrap.Constants {
	return container.Const
}

func ProvideEnv(container *bootstrap.Di) *bootstrap.Env {
	return container.Env
}

func ProvideS3(container *bootstrap.Di) *bootstrap.S3 {
	return &container.Env.Storage
}

var KafkaElasticProviderSet = wire.NewSet(
	ElasticAndDatabaseProviderSet,
	ElRepoProviderSet,
	CdcServiceProviderSet,
	KafkaCdcProviderSet,
)

var ProviderSet = wire.NewSet(
	DatabaseProviderSet,
	PkgProviderSet,
	RepoProviderSet,
	FileServiceProviderSet,
	ServiceProviderSet,
	HandlerProviderSet,
	MiddlewareProviderSet, seed.NewSeeder,
)

type Middlewares struct {
	Recovery       *panicwall.PanicWall
	RateLimit      *midratelimit.RateLimit
	Authentication *midauth.Authentication
	Upgrader       *midupgrader.WebSocketUpgrader
}

type Handlers struct {
	FileHandler    *handlers.FileHandler
	UserHandler    *handlers.UserHandler
	ProjectHandler *handlers.ProjectHandler
	GeneralHandler *handlers.GeneralHandler
	PaymentHandler *handlers.PaymentHandler
	BidHandler     *handlers.BidHandler
	TeamHandler    *handlers.TeamHandler
	RoleHandler    *handlers.RoleHandler
	ChatHandler    *handlers.ChatHandler
}

type Application struct {
	Handlers    *Handlers
	Middlewares *Middlewares
	Seeder      *seed.Seeder
}

type ElasticApp struct {
	KafkaCdc *consumer.KafkaCdc
}
