// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/niflheimdevs/backend/bootstrap"
	"github.com/niflheimdevs/backend/internal/application/services"
	"github.com/niflheimdevs/backend/internal/application/services/impl"
	"github.com/niflheimdevs/backend/internal/delivery/http/handlers"
	"github.com/niflheimdevs/backend/internal/delivery/http/middlewares/authentication"
	"github.com/niflheimdevs/backend/internal/delivery/http/middlewares/exceptions"
	"github.com/niflheimdevs/backend/internal/delivery/http/middlewares/ratelimit"
	"github.com/niflheimdevs/backend/internal/domain/repositories/postgres"
	"github.com/niflheimdevs/backend/internal/domain/repositories/postgres/transaction"
	"github.com/niflheimdevs/backend/internal/domain/repositories/redis"
	"github.com/niflheimdevs/backend/internal/domain/repositories/storage"
	"github.com/niflheimdevs/backend/internal/infrastructure/db/driver"
	"github.com/niflheimdevs/backend/internal/infrastructure/db/transaction"
	"github.com/niflheimdevs/backend/internal/infrastructure/repositories/postgres"
	"github.com/niflheimdevs/backend/internal/infrastructure/repositories/redis"
	"github.com/niflheimdevs/backend/internal/infrastructure/repositories/storage"
	"github.com/niflheimdevs/backend/pkg"
)

// Injectors from wire.go:

func InitializeApplication(container *bootstrap.Di) (*Application, error) {
	constants := ProvideConstants(container)
	fileStorage := storageimpl.NewFileStorage()
	fileService := servicesimpl.NewFileService(fileStorage)
	jwt := servicesimpl.NewJWT(constants)
	validate := pkg.NewValidator()
	fileHandler := handlers.NewFileHandler(constants, fileService, jwt, validate)
	pool := driver.ConnectSQL(container)
	userRepo := repositoriesimpl.NewUserRepo(pool)
	client := driver.ConncetRedis(container)
	userCache := redisimpl.NewUserCache(client)
	secretSauce := pkg.NewSecretSauce()
	userService := servicesimpl.NewUserService(userRepo, userCache, constants, fileService, secretSauce)
	tagRepo := repositoriesimpl.NewTagRepo(pool)
	tagService := servicesimpl.NewTagService(tagRepo, userRepo)
	careerRepo := repositoriesimpl.NewCareerRepo(pool)
	careerService := servicesimpl.NewCareerService(careerRepo, tagService, tagRepo, userRepo)
	smsService := servicesimpl.NewSmsService()
	userHandler := handlers.NewUserHandler(constants, userService, jwt, validate, tagService, careerService, smsService)
	errorHandler := handlers.NewErrorHandler()
	projectRepo := repositoriesimpl.NewProjectRepo(pool, tagRepo)
	paymentRepo := repositoriesimpl.NewPaymentRepo(pool)
	pgxTxManager := db.NewTxManager(pool)
	paymentService := servicesimpl.NewPaymentService(paymentRepo, pgxTxManager)
	projectService := servicesimpl.NewProjectService(projectRepo, paymentService, constants, tagRepo, pgxTxManager)
	labelRepo := repositoriesimpl.NewLabelRepo(pool)
	labelService := servicesimpl.NewLabelService(labelRepo, userRepo)
	projectHandler := handlers.NewProjectHandler(constants, projectService, userService, labelService, jwt, validate)
	generalHandler := handlers.NewGeneralHandler(tagService, careerService, labelService, jwt, constants, validate)
	paymentHandler := handlers.NewPaymentHandler(paymentService, constants, validate)
	wireHandlers := &Handlers{
		FileHandler:    fileHandler,
		UserHandler:    userHandler,
		ErrorHandler:   errorHandler,
		ProjectHandler: projectHandler,
		GeneralHandler: generalHandler,
		PaymentHandler: paymentHandler,
	}
	panicWall := panicwall.NewPanicWall()
	rateLimit := midratelimit.NewRateLimit()
	authentication := midauth.NewAuth(constants, jwt)
	middlewares := &Middlewares{
		Recovery:       panicWall,
		RateLimit:      rateLimit,
		Authentication: authentication,
	}
	application := &Application{
		Handlers:    wireHandlers,
		Middlewares: middlewares,
	}
	return application, nil
}

// wire.go:

var DatabaseProviderSet = wire.NewSet(driver.ConnectSQL, driver.ConncetRedis, db.NewTxManager, wire.Bind(new(transaction.TxManager), new(*db.PgxTxManager)))

var PkgProviderSet = wire.NewSet(pkg.NewValidator, pkg.NewSecretSauce)

var RepoProviderSet = wire.NewSet(repositoriesimpl.NewUserRepo, repositoriesimpl.NewProjectRepo, repositoriesimpl.NewCareerRepo, repositoriesimpl.NewTagRepo, repositoriesimpl.NewLabelRepo, repositoriesimpl.NewPaymentRepo, storageimpl.NewFileStorage, redisimpl.NewUserCache, wire.Bind(new(repositories.UserRepo), new(*repositoriesimpl.UserRepo)), wire.Bind(new(repositories.TagRepo), new(*repositoriesimpl.TagRepo)), wire.Bind(new(repositories.CareerRepo), new(*repositoriesimpl.CareerRepo)), wire.Bind(new(repositories.LabelRepo), new(*repositoriesimpl.LabelRepo)), wire.Bind(new(repositories.ProjectRepo), new(*repositoriesimpl.ProjectRepo)), wire.Bind(new(repositories.PaymentRepo), new(*repositoriesimpl.PaymentRepo)), wire.Bind(new(storage.FileStorage), new(*storageimpl.FileStorage)), wire.Bind(new(redis.UserCache), new(*redisimpl.UserCache)))

var FileServiceProviderSet = wire.NewSet(servicesimpl.NewFileService, wire.Bind(new(services.FileService), new(*servicesimpl.FileService)))

var ServiceProviderSet = wire.NewSet(servicesimpl.NewUserService, servicesimpl.NewTagService, servicesimpl.NewCareerService, servicesimpl.NewLabelService, servicesimpl.NewProjectService, servicesimpl.NewPaymentService, servicesimpl.NewSmsService, servicesimpl.NewJWT, wire.Bind(new(services.UserService), new(*servicesimpl.UserService)), wire.Bind(new(services.TagService), new(*servicesimpl.TagService)), wire.Bind(new(services.CareerService), new(*servicesimpl.CareerService)), wire.Bind(new(services.LabelService), new(*servicesimpl.LabelService)), wire.Bind(new(services.ProjectService), new(*servicesimpl.ProjectService)), wire.Bind(new(services.PaymentService), new(*servicesimpl.PaymentService)), wire.Bind(new(services.SmsService), new(*servicesimpl.SmsService)), wire.Bind(new(services.JWT), new(*servicesimpl.JWT)), ProvideConstants)

var HandlerProviderSet = wire.NewSet(handlers.NewFileHandler, handlers.NewUserHandler, handlers.NewErrorHandler, handlers.NewProjectHandler, handlers.NewGeneralHandler, handlers.NewPaymentHandler, wire.Struct(new(Handlers), "*"))

var MiddlewareProviderSet = wire.NewSet(midratelimit.NewRateLimit, midauth.NewAuth, panicwall.NewPanicWall, wire.Struct(new(Middlewares), "*"))

func ProvideConstants(container *bootstrap.Di) *bootstrap.Constants {
	return container.Const
}

var ProviderSet = wire.NewSet(
	DatabaseProviderSet,
	PkgProviderSet,
	RepoProviderSet,
	FileServiceProviderSet,
	ServiceProviderSet,
	HandlerProviderSet,
	MiddlewareProviderSet,
)

type Middlewares struct {
	Recovery       *panicwall.PanicWall
	RateLimit      *midratelimit.RateLimit
	Authentication *midauth.Authentication
}

type Handlers struct {
	FileHandler    *handlers.FileHandler
	UserHandler    *handlers.UserHandler
	ErrorHandler   *handlers.ErrorHandler
	ProjectHandler *handlers.ProjectHandler
	GeneralHandler *handlers.GeneralHandler
	PaymentHandler *handlers.PaymentHandler
}

type Application struct {
	Handlers    *Handlers
	Middlewares *Middlewares
}
