package enums

type GeneralError string
type SpecificError string

const (
	EMAIL_TAKEN   SpecificError = "EMAIL_TAKEN"
	EMAIL_INVALID SpecificError = "EMAIL_INVALID"

	USERNAME_TAKEN   SpecificError = "USERNAME_TAKEN"
	USERNAME_INVALID SpecificError = "USERNAME_INVALID"

	PHONE_INVALID SpecificError = "PHONE_INVALID"
	PHONE_TAKEN   SpecificError = "PHONE_TAKEN"

	PASSWORD_INVALID    SpecificError = "PASSWORD_INVALID"
	PASSWORD_TOO_SHORT  SpecificError = "PASSWORD_TOO_SHORT"
	PASSWORD_TOO_LONG   SpecificError = "PASSWORD_TOO_LONG"
	PASSWORD_NO_DIGIT   SpecificError = "PASSWORD_NO_DIGIT"
	PASSWORD_NO_CAPITAL SpecificError = "PASSWORD_NO_CAPITAL"
	PASSWORD_NO_SMALL   SpecificError = "PASSWORD_NO_SMALL"

	OTP_INVALID                SpecificError = "OTP_INVALID"
	OTP_EXPIRED_OR_BAD_SESSION SpecificError = "OTP_EXPIRED_OR_BAD_SESSION"

	DATABASE_ERROR      SpecificError = "DATABASE_ERROR"
	MICROSERVICE_ERROR  SpecificError = "MICROSERVICE_ERROR"
	SERVICE_UNAVAILABLE SpecificError = "SERVICE_UNAVAILABLE"

	AUTH_INVALID_CREDENTIALS SpecificError = "AUTH_INVALID_CREDENTIALS"
	AUTH_TOKEN_EXPIRED       SpecificError = "AUTH_TOKEN_EXPIRED"
	AUTH_ACCESS_DENIED       SpecificError = "AUTH_ACCESS_DENIED"

	MISSING_REQUIRED_FIELD SpecificError = "MISSING_REQUIRED_FIELD"

	CACHE_ERROR SpecificError = "CACHE_ERROR"
)

const (
	VALIDATION_ERROR GeneralError = "VALIDATION_ERROR"
	INTERNAL_ERROR   GeneralError = "INTERNAL_ERROR"
	NOT_FOUND        GeneralError = "NOT_FOUND"
	BAD_REQUEST      GeneralError = "BAD_REQUEST"
	// OTPError         GeneralError = "OTPError"
)
