name: CD

on:
  push:
    branches:
      - develop
      - Fix/HTMLEmail
jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write .env file
        run: | 
            echo "${{ secrets.ENV_FILE }}" > .env
      
      - name: Write .pem files
        run: |
            mkdir ./internal/jwt
            echo "${{ secrets.PRIVATEJWTKEY }}" > ./internal/jwt/privateKey.pem
            echo "${{ secrets.PUBLICJWTKEY }}" > ./internal/jwt/publicKey.pem
            mkdir ./SSL
            echo "${{ secrets.SSLPRIVATEKEY }}" > ./SSL/privatekey.key
            echo "${{ secrets.SSLCERT }}" > ./SSL/certificate.pem
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PAT }}
      - name: Build and Push Docker Image
        run: |
          docker compose build
          docker compose push

      - name: Copy docker-compose
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "docker-compose.yaml"
          target: "/home/niflheim/Desktop/backend"
      
      - name: Copy configs
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "configs/*"
          target: "/home/niflheim/Desktop/backend"
        
      - name: Copy scripts
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "scripts/*"
          target: "/home/niflheim/Desktop/backend" 

      # - name: Ensure html-templates directory exists
      #   uses: appleboy/ssh-action@v0.1.8
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     script: |
      #       mkdir -p ./internal/application/email_templates

      - name: Copy html-templates and logo
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "internal/application/email_templates/"
          target: "/home/niflheim/Desktop/backend"

      - name: Copy init.sql
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "migrations/init.sql"
          target: "/home/niflheim/Desktop/backend"

      - name: Copy triggers.sql
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "migrations/triggers.sql"
          target: "/home/niflheim/Desktop/backend"
          
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/niflheim/Desktop/backend
            echo "${{ secrets.ENV_FILE }}" > .env
            chmod 644 .env
            
            docker container prune
            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d
            docker image prune -f
